.travis.yml
coco/master.py

fix(master): use UTC timestamp for comet

---

coco/__init__.py
coco/endpoint.py
coco/master.py
coco/result.py
coco/state.py
conf/coco.conf
conf/endpoints/gains.conf
conf/endpoints/start.conf

- request values can be saved in state
- request values can get loaded from state
Closes #10

feat: Add State class to keep track of configs

---

coco/endpoint.py
coco/result.py
conf/coco.conf
scripts/coco-client

Add a client script

---

coco/__init__.py
coco/endpoint.py
coco/master.py
coco/scheduler.py
coco/worker.py
conf/coco.conf
docs/endpoint.rst

- Moved scheduler to worker process.
- Added option to specify conditions for scheduled endpoints to be called.

Schedule conditions

---

.coveragerc
coco/test/endpoint_farm.py

- exclude _version.py
- exclude unit test framework errors

ci(coverage): exclude some code

---

coco/request_forwarder.py
tests/test_metrics.py

Note that I also found and fixed a bug in the metrics initialisation.

unit test for metrics

---

.travis.yml
coco/__init__.py
coco/blacklist.py
coco/endpoint.py
coco/exceptions.py
coco/master.py
coco/request_forwarder.py
coco/util.py
coco/worker.py
requirements.txt
tests/test_blacklist.py
tests/test_metrics.py
tests/test_persistentstate.py

For the moment I have (begrudgingly) gone for the non RESTful `/blacklist` and `/update-blacklist` endpoints as I figured we could add that support in a later pull request.

Blacklist support

---

coco/__init__.py
coco/endpoint.py
coco/master.py
coco/request_forwarder.py
coco/result.py
coco/test/endpoint_farm.py
coco/wait.py
conf/endpoints/gps-time.conf
conf/endpoints/restart-cluster.conf
docs/endpoint.rst
tests/test_metrics.py
tests/test_on_failure.py
tests/test_wait.py

- feat(endpoint) allow to add to forward request data
- feat: add internal endpoint /wait
- feat(conf): add endpoint /restart-cluster

Add endpoint: /restart-cluster

---

coco/master.py
coco/request_forwarder.py
tests/test_metrics.py
tests/test_queue.py

Limit queue length

---

coco/master.py

cache redis script

---

coco/endpoint.py
coco/master.py
coco/request_forwarder.py
coco/test/endpoint_farm.py
coco/worker.py
tests/test_forward.py

Forward URL arguments

---

coco/config.py
coco/master.py
scripts/coco-client

Also loads config from a set of standard paths which are merged in
order.

refactor(config): centralise config processing/validation

---

coco/request_forwarder.py

feat(request_forwarder): add queue length metric

---

coco/config.py
coco/master.py
coco/request_forwarder.py
tests/test_timeout.py

feat(request_forwarder): make timeout configurable 

---

coco/blacklist.py
coco/endpoint.py
scripts/coco-client

feat(client): add blacklist endpoints

---

coco/config.py
coco/master.py

hopefully fixes the `NoneType: None` errors.

Add REQUEST_TIMEOUT to sanic frontend

---

coco/state.py
requirements.txt

https://github.com/kotekan/kotekan/issues/477
Alse see https://github.com/kotekan/kotekan/pull/499

Use msgpack for state hashing

---

.travis.yml
coco/master.py
coco/state.py
coco/test/coco_runner.py
coco/util.py
requirements.txt
scripts/coco
tests/simulate-chime/coco.conf
tests/test_metrics.py
tests/test_queue.py

Use the blacklist's `PersistentState` to make `State` persistent.
Add endpoint to flush state (reloads initial state from disk).

Make state persistent

---

coco/state.py
tests/config.yaml
tests/hash.cpp

When generating a state hash, all dicts where sorted before hashing.
This now also includes dicts inside lists.

fix(state): when hashing recurse on list elements

---

.travis.yml
coco/endpoint.py
coco/metric.py
coco/test/coco_runner.py
scripts/coco

feat(coco client): Improve output & show progress

---

coco/master.py
coco/state.py
coco/test/coco_runner.py
scripts/cocod
tests/test_save_state.py

To reset the state on start.
Closes #184

feat(cocod): add option --reset

---

coco/endpoint.py

fix(endpoint): remove multiple-exception catch

---

coco/master.py
scripts/cocod

Don't really start, just load config and exit.
Needed for https://github.com/chime-experiment/ch_ansible/issues/82

feat(cocod): add option --check-config

---

coco/__init__.py
coco/blocklist.py
coco/config.py
coco/core.py
coco/master.py
coco/request_forwarder.py
coco/test/coco_runner.py
docs/config.rst
scripts/coco
scripts/cocod
tests/simulate-chime/coco.conf
tests/simulate-chime/test_client.py
tests/test_blacklist.py
tests/test_persistentstate.py

Rename blacklist and master

---

coco/metric.py
coco/request_forwarder.py
coco/worker.py

fix: use 127.0.0.1 instead of localhost

---

CHANGELOG.md
coco/util.py

fix(util): copy list before sorting

---

coco/request_forwarder.py

Adds a histogram metric that observes the response times for requests
coco sends to external endpoints.
Closes #229

feat(request_forwarder): add metric for external response times

---

.github/workflows/main.yml
coco/check.py
coco/config.py
coco/endpoint.py
docs/endpoint.rst
pylint-ignore.md

Required for https://github.com/chime-experiment/ch_ansible/pull/279

Improve logging

---

coco/config.py
coco/core.py
coco/request_forwarder.py
coco/test/endpoint_farm.py
docs/conf.py
requirements.txt
tests/test_checks.py
tests/test_on_failure.py
tests/test_timeout.py

This adds a config option for toggling the tracing of connections when they encounter an exception.

Trace connections on exception

---

.github/workflows/main.yml
coco/__init__.py
coco/_version.py
coco/blocklist.py
coco/check.py
coco/config.py
coco/core.py
coco/endpoint.py
coco/request_forwarder.py
coco/result.py
coco/slack.py
coco/state.py
coco/test/coco_runner.py
coco/test/endpoint_farm.py
coco/wait.py
coco/worker.py
docs/conf.py
requirements.txt
setup.py
tests/test_on_failure.py

Make compatible with aioredis version 2.

Aioredis v2

---

requirements.txt

c.f. https://github.com/chime-experiment/comet/pull/99

fix(build): fix requirements.txt after comet merge
